#ifndef _DORMOUSEENGINE_GRAPHICS_PRIMITIVETOPOLOGY_HPP_
#define _DORMOUSEENGINE_GRAPHICS_PRIMITIVETOPOLOGY_HPP_

#include <string>

#include <D3DCommon.h>

#include "dormouse-engine/enums.hpp"

namespace dormouse_engine {
namespace graphics {


DE_ENUM_VALUES(
	PrimitiveTopology,
	(INVALID)(D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED)
	(POINT_LIST)(D3D11_PRIMITIVE_TOPOLOGY_POINTLIST)
	(TRIANGLE_LIST)(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST)
	(TRIANGLE_STRIP)(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP)
	(PATCH_LIST_4_CONTROL_POINTS)(D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST)
	);

} // namespace graphics
} // namespace dormouse_engine

#endif /* _DORMOUSEENGINE_GRAPHICS_PRIMITIVETOPOLOGY_HPP_ */
